[font]
size = 16.0
normal = { family = "JetBrainsMonoNL Nerd Font" }

[keyboard]
bindings = [
  { key = "H", mods = "Command|Shift", action = "SelectPreviousTab" },
  { key = "L", mods = "Command|Shift", action = "SelectNextTab" },
  { key = "A", mods = "Command", chars = "\u0001" },
]
