# preload = ~/Pictures/Wallpapers/gracile.jpg
# wallpaper = HDMI-A-1,~/Pictures/Wallpapers/gracile.jpg
# wallpaper = DP-1,~/Pictures/Wallpapers/gracile.jpg
# splash = false
# wallpaper = HDMI-A-1,~/Pictures/Wallpapers/gracile.jpg
# wallpaper = DP-1,~/Pictures/Wallpapers/gracile.jpg

wallpaper {
    monitor = 
    path = ~/Pictures/Wallpapers/gracile.jpg
    fit_mode = cover
}
splash = false
